### ISSUE TITLE
Error occurs when GeoJSON's points are clicked

### ISSUE THREAD

**Issue by rot1024** [reearth/reearth#108]
**Describe the bug**

When I load the geojson of the point data from the file, when I click on a plotted point, the edit page reloads and the error message "invaild ID" appears at the top. This is a repeat of the same process.

**To Reproduce**

1. Go to editor
2. Add a "file" layer
3. Select GeoJSON file contains point data
4. Select points newly appears on the Earth

**Expected behavior**

No error, no infobox

**Comment by lavalse** [comment]
Seem fixed. But click the point will not change anything.
