### ISSUE TITLE
improve UI of the documentation

### ISSUE THREAD

**Issue by kiibo382** [reearth/reearth#133]
## issue: it's hard to read the documentation in terms of UI.
In terms of sentence structure, it's easy to read, but hard to read in terms of UI.
For example, sidebar is not displaying well.
![image](https://user-images.githubusercontent.com/64523345/136676485-601f23c3-35ad-4a29-841d-8dc0d6513592.png)

In addition, no next button and back button.

## solution: Change docuras settings
Change docuras settings to change sidebar and add Next and Back buttons.
(refer to: https://docusaurus.io/docs/next/sidebar)

**Comment by HideBa** [comment]
@kiibo382 Thank you for opening this issue. Since we fully changed our product page. I'll close this issue.
