### ISSUE TITLE
Project setting page does not display correctly after creating a new project

### ISSUE THREAD

**Issue by rot1024** [reearth/reearth#168]
**To Reproduce**

1. Create a new project
2. Jump to the setting page of the project  newly created (do not show editor page)
3. Project name and left menus of the project doesn't display (reloading fixes it)

**Expected behavior**

Project name and left menus of the project should display

**Screenshots**

![image](https://user-images.githubusercontent.com/3888696/140696625-7395af28-7343-4f6c-91f3-f65b789f7774.png)

**Comment by HideBa** [comment]
Since we had released this feature, I close this PBL.
