### ISSUE TITLE
Camera shifts slightly when you set the location

### ISSUE THREAD

**Issue by arisamikumo** [reearth/reearth#178]
**Describe the bug**
カメラ設定する時、
1. マウスで好きな位置に持っていく
2. キャプチャ押す
と少し位置がずれる
-------
When you set up the camera, you can
1. Move the mouse to the desired position.
2. press capture
and the position will be shifted a little.

**To Reproduce**
1. Go to Camera setting
2. Click on Edit
3. Move the map
4. Click on Capture

**Expected behavior**
Captured at the position exact where it was moved.

**Screenshots**
https://user-images.githubusercontent.com/53960439/143386564-57cee383-e7f7-46bf-b013-018ccfce4b72.mp4

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Version ?

**Smartphone (please complete the following information):**
Didin't try

**Additional context**
カメラ位置をメモリで調整する場合は、ずれない。
If the camera position is adjusted by memory, it will not shift.

**Comment by lavalse** [comment]
fixed by shaun
