### ISSUE TITLE
Terrain feature enhancement

### ISSUE THREAD

**Issue by rot1024** [reearth/reearth#181]
## Leader

@rot1024

## User story and test cases

- [ ] Users want to switch terrain type to display highly accurate terrain data: e.g. Cesium world terrain, ArcGIS terrain (default is cesium)
- [ ] Users want to emphasize the terrain by specifying the magnification factor (default is 1x)
- [ ] Users want to change a relative height as a reference for terrain highlighting (default is 0)

**Comment by HideBa** [comment]
Since we had released this feature, I close this PBL.
