### ISSUE TITLE
Marker image overshadow labels

### ISSUE THREAD

**Issue by rot1024** [reearth/reearth#184]
<img width="523" alt="スクリーンショット 2021-11-30 12 57 34" src="https://user-images.githubusercontent.com/3888696/143988667-fc9533f2-3aa2-4f91-af1f-8aacf6afa29b.png">

**Comment by issmail-basel** [comment]
@rot1024 , seems there is no solution available by Cesium (same issue I had with clusters).
https://github.com/CesiumGS/cesium/issues/4108
https://groups.google.com/g/cesium-dev/c/cbypD-8kaSc/m/nVLFVlrKBQAJ
https://community.cesium.com/t/on-2d-mode-polylines-are-always-on-top-of-labels/11451

The only workaround is to change the `eyeOffset` property of label, maybe add it as a panel property? let me know what you think.
