### ISSUE TITLE
The style of  infobox block dropdown list is broken

### ISSUE THREAD

**Issue by lavalse** [reearth/reearth#203]
**Describe the bug**
- The style of  infobox block dropdown list is broken

**To Reproduce**
1. Create a new infobox
2. Add new block
3. If there are a lot of blocks, the style will be broken

**Screenshots**
![1](https://user-images.githubusercontent.com/3818046/150499961-7f823dda-c9c1-43f7-b774-84f19ec86df9.png)

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]

**Comment by HideBa** [comment]
Since we had released this bug fix, I close this bug issue.
