### ISSUE TITLE
Block Plugins Bugs

### ISSUE THREAD

**Issue by lavalse** [reearth/reearth#204]
**Describe the bug**
- Delete feature bug: Create a block plugin, but user can't delete that block any more
- Select feature bug: While Selecting from different plugin blocks, user have to unselect one, and then he can select another one 😓

**To Reproduce**
just check the screenshots

**Screenshots**
![2](https://user-images.githubusercontent.com/3818046/150501454-6dd0f85c-dd64-42d2-b34a-c013c7eb9a9c.png)

![image](https://user-images.githubusercontent.com/3818046/150502020-0ec02f14-c5ea-4f8c-bc6f-f45dd63777ce.png)

**Comment by HideBa** [comment]
Since we had released this bug fix, I close this bug issue.
