### ISSUE TITLE
labeling hidden by marker symbol

### ISSUE THREAD

**Issue by nbayashi** [reearth/reearth#207]
**Describe the bug**
Marker’s label is hidden by icon image or point symbol.

**To Reproduce**
1. put Marker on the map
2. turn on label and set labeling text at marker's property
3. set Marker's icon image.(especially bigger size image)
4. label is hidden by icon

**Expected behavior**

label should be front of icon image.

**Screenshots**
![image](https://user-images.githubusercontent.com/13118515/150956548-7e67a739-e9d9-4d94-8034-09812e9fcf68.png)

**Desktop (please complete the following information):**
 - OS:iOS, Mac book 
 - Browser Chrom, safari

**Smartphone (please complete the following information):**

**Additional context**
this is occurred at Editor, preview and published page.

**Comment by issmail-basel** [comment]
Related to #184
