### ISSUE TITLE
bug of moving to photo overlay at story telling

### ISSUE THREAD

**Issue by nbayashi** [reearth/reearth#215]
**Describe the bug**
moving to photo overlay at story telling, camera will stops on the way.

**To Reproduce**
Put photo overlay layer and set overlay image.
Add story telling widget and set photo overlay layer on stories list.
When moving to photo overlay layer by clicking button of story telling, camera will stops and photo overlay image will be shown on the way without reaching photo overlay layer .

**Expected behavior**
if clicking button of story telling to move to photo overlay layer, overlay image will shown after camera reach to the layer without moving camera is stopped.

**Screenshots**
![タイトルなし](https://user-images.githubusercontent.com/13118515/152064767-db493708-cc21-4880-a90f-a4d85426d05c.gif)

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Browser [ chrome

**Comment by lavalse** [comment]
Temporary solution:
- Set StoryTelling ***General Duration***  to smaller then 2 s
