### ISSUE TITLE
Broken alignment inside settings pages

### ISSUE THREAD

**Issue by issmail-basel** [reearth/reearth#221]
**Describe the bug**
- Alignment of actions is not correct.

**Screenshots**
![1](https://user-images.githubusercontent.com/78056580/152457907-4035b4e6-456a-4564-a55d-d22b23493662.png)
![2](https://user-images.githubusercontent.com/78056580/152457910-efff8726-fc18-44a8-b981-004f041ca7fc.png)

**Comment by lavalse** [comment]
yes. Thanks. And please reference [here](https://www.figma.com/file/bdnfDaGXGoNfUws4y7JItl/Re%3AEarth-UI-Gamma?node-id=6989%3A238138)

I guess the component maybe a little mess. But if these properties can follow the design will be quite nice. If some is handling this, just let me know. we can have a quick talk
