### ISSUE TITLE
"ff" is added automatically after RGB code

### ISSUE THREAD

**Issue by arisamikumo** [reearth/reearth#237]
**Describe the bug**
When I entered color cord to Re:Earth, It’s automatically added “ff” its last.

**To Reproduce**
1. Go to a project
2. Type RGB code anywhere
3. "ff"  is added automatically after it 

**Expected behavior**
"ff" is not be added

**Screenshots**
<img width="261" alt="スクリーンショット 2022-03-04 18 00 02" src="https://user-images.githubusercontent.com/53960439/156732500-5d24c152-9fc8-435a-a028-4ac0d02e03f2.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser:Chrome
 - Version ??

**Comment by lavalse** [comment]
@arisamikumo @KaWaite 
![image](https://user-images.githubusercontent.com/3818046/165446863-c50aa74d-84aa-4720-b891-79a6b25d4ae6.png)
I came up with a new idea. Maybe we can change the placeholder text here. "#RRGGBBAA" show the last two space is for " alpha ". Is this idea ok?
