### ISSUE TITLE
Mobile storytelling: right nav button disappears

### ISSUE THREAD

**Issue by KaWaite** [reearth/reearth#239]
**Describe the bug**
In mobile, sometimes the right nav button disappears. Happened when the storytelling was on a primitive with a very long name. Also, the total stories was 15. Not sure it is because of the long name, the amount of widgets, or the combination pushing the right nav button out of sight

**Expected behavior**
The left and right nav buttons should always be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/34051327/156955494-229d36fd-8742-4f92-8993-d10a3c94f759.png)

**Smartphone (please complete the following information):**
 - Device: iphone 13
 - Browser: chrome

**Comment by lavalse** [comment]
For some reason. I didn't find this in my env 🤔
