### ISSUE TITLE
[FE]support custom webfont

### ISSUE THREAD

**Issue by yk-eukarya** [reearth/reearth#25]
## User story
Users currently only have a choice of fonts from Re:Earth, and would like to use their own webfont with Infobox, Label, etc. We would like to use unique webfonts for Infobox, Label, etc. This will give us a wider range of design option

## Requirements
* Can input webfont URL or JS code
* The fonts which are added by users can be chosen from the fonts pull-down list
* Web font works on published page as well
- [ ] write document
   - [ ] Front-end
   - [ ] Back-end

- [https://github.com/typekit/webfontloader](https://github.com/typekit/webfontloader) is recommended 👍  (@rot 1024)
    - 👆 supports google, typekit, monotype, fontdeck

**Comment by HideBa** [comment]
Since we don't have a plan to develop this soon, I'll close this.
