### ISSUE TITLE
Wrong title for adding layers into cluster modal

### ISSUE THREAD

**Issue by lavalse** [reearth/reearth#281]
**Screenshots**
![1652258755(1)](https://user-images.githubusercontent.com/3818046/168029865-da94ed48-da87-45ed-99c3-5b7b188bb095.png)

**Additional context**
Need design

**Comment by airslice** [comment]
I don't know if anyone has fix this or the issue description needs update. I've test on local and test env the layer title works fine on this modal. BUT the layers coming from a dataset not. If this issue refers to the dataset ones then i think maybe the question is how to determin the title from the dataset. The titles are alreay empty when imported into layers from dataset (at least in my test).
