### ISSUE TITLE
Plugin API to add layer

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth#294]
## User story
The user wants to add layers from a plug-in. For example, when developing a plug-in that displays the current location, or a plug-in that acquires data from an external source and displays it on a map, this is not possible because layers cannot be added. Supporting this feature would further increase what plug-ins can do on the post-publication page and encourage the development of more versatile plug-ins.

## Requirements
Plugin API should expose the functionality which allows plugins to add layers
- Plugins can get the list of 'extenstionId' of layers
- Plugin can add layers with selected extension ID
- 
## Testing list
- [ ]

**Comment by airslice** [comment]
About the `getExtensionIds` API i got some comments [here](https://github.com/reearth/reearth-web/pull/258#discussion_r912603819). I agree and also think provide the supported types in the API document is better. I've removed this API from code.
