### ISSUE TITLE
[FE]: Plan for Event API

### ISSUE THREAD

**Issue by KaWaite** [reearth/reearth#299]
Plan out api changes for issue #298 . 

Needs approval from @rot1024 before starting 298.

**Comment by airslice** [comment]
From the previous conversiton i found the basic plan (from @rot1024) as:
- Add a new method to the EngineRef type in Visualizer/Engine.
- Visualizer/Engine/Cesium then exposes an implementation of that method.
- In visualizer/Plugin, simply call that method when the plugin API is called.
