### ISSUE TITLE
Add option to use OSM 3D building

### ISSUE THREAD

**Issue by HideBa** [reearth/reearth#329]
## User story
Currently, PLATEAU data and other 3D data can be imported and used. On the other hand, there are some areas, such as PLATEAU, where 3D city models are not well developed. Such users would like to use OSM Building to take advantage of 3D maps. Therefore, an option to enable OSM Buildings will be installed to allow more representations.

## Examples
https://cesium.com/platform/cesium-ion/content/cesium-osm-buildings/

## Testing list
- [ ]

**Comment by lavalse** [comment]
Design file is [here](https://www.figma.com/file/bdnfDaGXGoNfUws4y7JItl/Re%3AEarth-UI-Gamma?node-id=11576%3A179143)
