### ISSUE TITLE
Update dataset setting page

### ISSUE THREAD

**Issue by issmail-basel** [reearth/reearth#33]
![image](https://user-images.githubusercontent.com/3818046/138983218-a1c27ee3-b49f-4658-ae57-3ef07dc09457.png)

👆 still using the old style, which is ok, but just a little different from other page and the whole design system.
If can update like 👇 will be much better.

![image](https://user-images.githubusercontent.com/3818046/138983538-f4b1870a-468f-4ad0-9210-489a8a819f37.png)
File is [here](https://www.figma.com/file/bdnfDaGXGoNfUws4y7JItl/Re%3AEarth-UI-Gamma?node-id=4065%3A6179)

------

And also need to think about in this page, the `add dataset` button can only support uploading file from local, should we also need to support uploading data from Google spread sheet ?

**Comment by lavalse** [comment]
The assets library on the setting page is finished. But the datasets library is still the old type. And not sure we want to update it or not.
