### ISSUE TITLE
Some uploaded images aren't shown on asset modal

### ISSUE THREAD

**Issue by KaWaite** [reearth/reearth#6]
**Describe the bug**
The assets which had been uploaded from the asset modal are not shown there.

**To Reproduce**
1. Open asset modal
2. Upload image(The number of total image should be more than 10)
3. You won't see images you've just uploaded there
4. Go to settings page, asset section
5. The images are there(Image can be uploaded, but not fetched on front-end)

**Expected behavior**
All uploaded images should be shown.

**Comment by HideBa** [comment]
We can't reproduce this bug anymore.
