### ISSUE TITLE
Change selecting indicator

### ISSUE THREAD

**Issue by mimoham24** [reearth/reearth#68]
# Leader
@nina992 
## User story
Users want to change the indicator which is used when the layer is selected because the design of the project is sometimes restricted with that.
If they can do that, more expression can be created by them.
Also, plugin API should also support changing the indicator from plugins. 

![スクリーンショット 2021-07-14 13 27 04](https://user-images.githubusercontent.com/49897538/125561325-618e4ca0-d249-4767-adea-4c2e15cdb996.png)

## Requirements
- [ ] User can choose the indicator from a preset list
- [ ] User can also upload their own image which can be used as an indicator
- [ ] On the published page, the indicator set by the user is available
- [ ] Plugin exposes the API to set indicator from external

## Completion condition

- [ ] All PRs were passed CI, code-reviewed, and merged
- [ ] Tested on staging env
- [ ] Released in the production env
- [ ] A demonstration was held

**Comment by lavalse** [comment]
[Here](https://www.figma.com/file/bdnfDaGXGoNfUws4y7JItl/Re%3AEarth-UI-Gamma?node-id=10319%3A174052) is the design file, and please check it.

![image](https://user-images.githubusercontent.com/3818046/167757645-51836714-5ee5-4867-a9d4-030d28a5de46.png)
