### ISSUE TITLE
Making an infobox on dataset child doesn't replace dataset's infobox

### ISSUE THREAD

**Issue by KaWaite** [reearth/reearth#84]
**Describe the bug**
When you create an infobox on a dataset child when the dataset has an infobox, the child's infobox doesn't override the dataset's until a block is created.

**To Reproduce**
1. Add a dataset
2. Create a infobox on the dataset
3. Then, create an infobox on a child of the dataset
4. The dataset's (parent) infobox is shown still.

**Expected behavior**
When you create an infobox on a child of a dataset with an infobox, the child's infobox should be shown immediately.

**Additional context**
Clicking on one of the dataset's blocks after creating an infobox on a child will make the right panel go blank.
The infobox's merged values coming to the front-end from the back-end don't update unless the child's infobox has a box.

**Comment by HideBa** [comment]
Temporarily fixed. Still need to be discussed but it'll be another task.
