### ISSUE TITLE
Sphere is added on the same place

### ISSUE THREAD

**Issue by KaWaite** [reearth/reearth#9]
**Describe the bug**
When the sphere is added to the earth, sometimes it's added to the same location.

**To Reproduce**
1. add sphere from the toolbar
2. with selecting the sphere which has been added, add another sphere
3. the location of the second one will be the same as the first one although it's been dropped different location.

**Expected behavior**
Adding a new sphere should always be shown where it is dropped.

**Comment by HideBa** [comment]
We can't reproduce this bug.
